version: '3.8'

services: 
    warehouse: 
        image: postgres:9.6
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=dbt
            - POSTGRES_PASSWORD=dbt
            - POSTGRES_DB=dbt
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes: 
            - ./pgdata:/var/lib/postgresql/data
    
    dbt:
        build: 
            context: "./dbt"
            dockerfile: "Dockerfile"
        entrypoint: sh -c "dbt ls --profiles-dir profile --project-dir core && sleep infinity"